### ISSUE TITLE
Add clear option

### ISSUE THREAD

**Issue by vrunoa** [sindresorhus/first-run#2]
Hey @sindresorhus , I start using ```first-run```, first of all, really useful module. :+1: 
For testing purposes I have to clear the first run value several times, searching in your code I see you use this code to clear it;
```javascript
(new Configstore('first-run_first-run')).clear();
```
But in different projects, I would have to change the name, **'first-run_first-run'**, **'first-run_other-project'**,... so I add a ```clear``` option to ```firstRun```, and clear your project first-run like 
```javascript
firstRun({clear:true})
```
Here's the source;
[https://github.com/Urucas/first-run/blob/master/index.js#L20](https://github.com/Urucas/first-run/blob/master/index.js#L20)
Let me know if you think this functionality is OK for a PR.

**Comment by sindresorhus** [comment]
Sure, PR welcome with a test and doc changes ;)

**Comment by vrunoa** [comment]
Cool, I've already add the ```clear``` param in the [README.md](https://github.com/Urucas/first-run/blob/master/readme.md#clear) file, and a [test](https://github.com/Urucas/first-run/blob/master/test3.js), but i'm not happy with my test, I'll add a few more lines of code and start a PR.

**Comment by vrunoa** [comment]
Close this issue. Continue the conversation in the PR [https://github.com/sindresorhus/first-run/pull/3](https://github.com/sindresorhus/first-run/pull/3)
